### PR TITLE
Division title with member position translation

### LINKED ISSUE #96: Translate individual division title that includes MP vote
Could we please have the Ukrainian translation for this version of the individual division page title that includes MP vote positions:

> Олег Медуниця voted with the majority (Yes) on the division Поіменне голосування про проект Постанови про Тимчасову президію першої сесії Верховної Ради України восьмого скликання (№1001) - за основу та в цілому

See https://tvfy-ukraine.oaf.org.au/people/rada/Виборчому_округу_№157/Олег_Медуниця/divisions/2014-11-27/20

screen shot 2015-11-17 at 11 53 02 am

### PR DESCRIPTION
**Pull request by equivalentideas**
This is the translation for the title of the page showing home an individual MP voted on a vote. 
This closes https://github.com/OPORA/publicwhip/issues/96

Here’s some examples of the Ukrainian text this produces:
screen shot 2015-12-09 at 5 04 49 pm
screen shot 2015-12-09 at 5 04 40 pm
screen shot 2015-12-09 at 5 04 35 pm

Could you please check if these are correct @orybiy @lisoffsky ^^^ ?

Here are some of the pages where this will appear on rada4you:
- https://rada4you.org/people/rada/Донецька_область/Сергій_Сажко/divisions/2015-03-03/959
- https://rada4you.org/people/rada/Харківська_область/Олександр_Фельдман/divisions/2015-03-03/961
- https://rada4you.org/people/rada/Донецька_область/Сергій_Сажко/divisions/2015-04-09/1453

See an example of one of these pages in English here https://theyvoteforyou.org.au/people/representatives/wentworth/malcolm_turnbull/divisions/2014-10-22/7

### CODE REVIEW

**Comment by equivalentideas** [comment]
@henare @beastie87 could one of you please review this code and make any suggestions for improvement or merge if/when the tests pass?

**Comment by henare** [comment]
Nice work finally making it through this complexity.

The "in the majority/minority" part of the sentence only takes into consideration yes/no votes. I guess you could argue that's the only _actual_ vote but it's a bit of a tortured argument.

I think we'll have to tweak something there but let's merge this as a first pass.

**Comment by henare** [comment]
Deploying :rocket: with:

```
bundle exec mina ukraine-production deploy
```

**Comment by henare** [comment]
Deployed :shipit:

**Comment by equivalentideas** [comment]
> The "in the majority/minority" part of the sentence only takes into consideration yes/no votes. I guess you could argue that's the only actual vote but it's a bit of a tortured argument.
> 
> I think we'll have to tweak something there but let's merge this as a first pass.

Sounds good to me :+1: Thanks :whale:

**Pull request merged**
