### PR TITLE
Licencing page

### PR DESCRIPTION
**Pull request by henare**
Translates the licencing page (#131).

I've also opened #166 for the untranslated bit.

@equivalentideas @beastie87 can someone please review and merge?

### CODE REVIEW

**Comment by equivalentideas** [comment]
Looks good to me :+1: I'll merge

**Comment by equivalentideas** [comment]
I'll just wait for the testing to pass :snail:

**Comment by equivalentideas** [comment]
:shipit: I'll now deploy this with:

```
bundle exec mina ukraine-production deploy
```

**Comment by equivalentideas** [comment]
Deployed https://rada4you.org/help/licencing

:fireworks: :fireworks: :fireworks:

**Comment by henare** [comment]
Awesome, thanks @equivalentideas :sparkles:

**Pull request merged**
